sat_act = [
    'District 2022 SAT/ACT: All Students, % Above Criterion',
    'District 2022 SAT/ACT: African American Students, % Above Criterion',
    'District 2022 SAT/ACT: American Indian Students, % Above Criterion',
    'District 2022 SAT/ACT: Asian Students, % Above Criterion',
    'District 2022 SAT/ACT: Hispanic Students, % Above Criterion',
    'District 2022 SAT/ACT: Two or More Races Students, % Above Criterion',
    'District 2022 SAT/ACT: Pacific Islander Students, % Above Criterion',
    'District 2022 SAT/ACT: White Students, % Above Criterion',
    'District 2022 SAT/ACT: Special Ed Students, % Above Criterion',
    'District 2022 SAT/ACT: Econ Disadv Students, % Above Criterion',
    'District 2022 SAT/ACT: EL Students, % Above Criterion',
    'District 2022 SAT/ACT: All Students, % Test-Taking',
    'District 2022 SAT/ACT: African American Students, % Test-Taking',
    'District 2022 SAT/ACT: American Indian Students, % Test-Taking',
    'District 2022 SAT/ACT: Asian Students, % Test-Taking',
    'District 2022 SAT/ACT: Hispanic Students, % Test-Taking',
    'District 2022 SAT/ACT: Two or More Races Students, % Test-Taking',
    'District 2022 SAT/ACT: Pacific Islander Students, % Test-Taking',
    'District 2022 SAT/ACT: White Students, % Test-Taking',
    'District 2022 SAT/ACT: Special Ed Students, % Test-Taking',
    'District 2022 SAT/ACT: Econ Disadv Students, % Test-Taking',
    'District 2022 SAT/ACT: EL Students, % Test-Taking',
    'District 2022 SAT/ACT: All Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: African American Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Hispanic Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: White Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: American Indian Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Asian Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Pacific Islander Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Two or More Races Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Econ Disadv Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: EL Students, % Graduates Above Criterion',
    'District 2022 SAT/ACT: Special Ed Students, % Graduates Above Criterion'
]

ap_ib = [
    'District 2022 AP/IB Course Completion Graduates: All Students Rate',
    'District 2022 AP/IB Course Completion Graduates: African American Rate',
    'District 2022 AP/IB Course Completion Graduates: Hispanic Rate',
    'District 2022 AP/IB Course Completion Graduates: White Rate',
    'District 2022 AP/IB Course Completion Graduates: American Indian Rate',
    'District 2022 AP/IB Course Completion Graduates: Asian Rate',
    'District 2022 AP/IB Course Completion Graduates: Pacific Islander Rate',
    'District 2022 AP/IB Course Completion Graduates: Two or More Races Rate',
    'District 2022 AP/IB Course Completion Graduates: Econ Disadv Rate',
    'District 2022 AP/IB Course Completion Graduates: Special Ed Rate',
    'District 2022 AP/IB Course Completion Graduates: EB/EL Rate',
    'District 2022 AP/IB: All Students (All Subjects) % Taking',
    'District 2022 AP/IB: African American (All Subjects) % Taking',
    'District 2022 AP/IB: American Indian (All Subjects) % Taking',
    'District 2022 AP/IB: Asian (All Subjects) % Taking',
    'District 2022 AP/IB: Hispanic (All Subjects) % Taking',
    'District 2022 AP/IB: Two or More Races (All Subjects) % Taking',
    'District 2022 AP/IB: Pacific Islander (All Subjects) % Taking',
    'District 2022 AP/IB: White (All Subjects) % Taking',
    'District 2022 AP/IB: Special Ed (All Subjects) % Taking',
    'District 2022 AP/IB: Econ Disadv (All Subjects) % Taking',
    'District 2022 AP/IB: EB/EL (All Subjects) % Taking',
    'District 2022 AP/IB: All Students (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: African American (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: American Indian (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Asian (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Hispanic (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Two or More Races (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Pacific Islander (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: White (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Special Ed (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: Econ Disadv (All Subjects) % Students Above Criterion',
    'District 2022 AP/IB: EB/EL (All Subjects) % Students Above Criterion',
]

longitudinal_graduation_rates = [
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for All Students Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for African American Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for American Indian Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Asian Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Hispanic Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Pacific Islander Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for White Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Two or More Races Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Econ Disadv Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for Special Ed Rate',
    'District 2022 4-Year Longitudinal: [FHSP-DLA Graduates] for EB/EL Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for All Students Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for African American Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for American Indian Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Asian Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Hispanic Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Pacific Islander Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for White Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Two or More Races Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Econ Disadv Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for Special Ed Rate',
    'District 2022 4-Year Longitudinal: [RHSP/DAP or FHSP-E/DLA Graduates] for EB/EL Rate',
]

chronic_absenteeism = [
    '2022 district Chronic Absenteeism All Students Group: Rate',
    '2022 district Chronic Absenteeism African American Group: Rate',
    '2022 district Chronic Absenteeism Hispanic Group: Rate',
    '2022 district Chronic Absenteeism White Group: Rate',
    '2022 district Chronic Absenteeism American Indian Group: Rate',
    '2022 district Chronic Absenteeism Asian Group: Rate',
    '2022 district Chronic Absenteeism Pacific Islander Group: Rate',
    '2022 district Chronic Absenteeism Two or More Races Group: Rate',
    '2022 district Chronic Absenteeism Econ Disadv Group: Rate',
    '2022 district Chronic Absenteeism Special Ed Group: Rate',
    '2022 district Chronic Absenteeism EL Group: Rate',
]

attendance_rates = [
   'District 2022 Attendance: All Students Rate',
    'District 2022 Attendance: Two or More Races Rate',
    'District 2022 Attendance: Asian Rate',
    'District 2022 Attendance: Pacific Islander Rate',
    'District 2022 Attendance: African American Rate',
    'District 2022 Attendance: Hispanic Rate',
    'District 2022 Attendance: White Rate',
    'District 2022 Attendance: American Indian Rate',
    'District 2022 Attendance: Econ Disadv Rate',
    'District 2022 Attendance: Special Ed Rate',
    'District 2022 Attendance: EB/EL Rate',
]

ccmr_rates = [
   'District 2022 College, Career, & Military Ready Graduates: All Students Rate',
    'District 2022 College, Career, & Military Ready Graduates: African American Rate',
    'District 2022 College, Career, & Military Ready Graduates: Hispanic Rate',
    'District 2022 College, Career, & Military Ready Graduates: White Rate',
    'District 2022 College, Career, & Military Ready Graduates: American Indian Rate',
    'District 2022 College, Career, & Military Ready Graduates: Asian Rate',
    'District 2022 College, Career, & Military Ready Graduates: Pacific Islander Rate',
    'District 2022 College, Career, & Military Ready Graduates: Two or More Races Rate',
    'District 2022 College, Career, & Military Ready Graduates: Econ Disadv Rate',
    'District 2022 College, Career, & Military Ready Graduates: Special Ed Rate',
    'District 2022 College, Career, & Military Ready Graduates: EB/EL Rate',
]

dropout_rates = [
   'All Students Dropout Rate',
    'African American Dropout Rate',
    'American Indian Dropout Rate',
    'Asian Dropout Rate',
    'Hispanic Dropout Rate',
    'Pacific Islander Dropout Rate',
    'Two or More Races Dropout Rate',
    'White Dropout Rate',
    'Econ Disadv Dropout Rate',
    'Special Ed Dropout Rate',
    'EB/EL Dropout Rate'
]

staar_results = [
    # Masters Grade Level
    'Mathematics (Masters Grade Level)',
    'Reading/ELA (Masters Grade Level)',
    'Writing (Masters Grade Level)',
    'Science (Masters Grade Level)',
    'Social Studies (Masters Grade Level)',

    # Meets Grade Level
    'Mathematics (Meets Grade Level)',
    'Reading/ELA (Meets Grade Level)',
    'Writing (Meets Grade Level)',
    'Science (Meets Grade Level)',
    'Social Studies (Meets Grade Level)',

    # Approaches Grade Level
    'Mathematics (Approaches Grade Level)',
    'Reading/ELA (Approaches Grade Level)',
    'Writing (Approaches Grade Level)',
    'Science (Approaches Grade Level)',
    'Social Studies (Approaches Grade Level)'
]

district_identifiers = [
    "DISTRICT_id",
    "TEA District Type",
    "TEA Description",
    "NCES District Type",
    "NCES Description",
    "Charter School (Y/N)", 
    "COUNTY",
    "REGION",
    "DISTRICT",
    "DISTNAME",
    "CNTYNAME",
    "DFLCHART",
    "DFLALTED",
    "ASVAB_STATUS"
]

outcome_mapping = {
    "SAT/ACT": sat_act,
    "AP/IB": ap_ib,
    "Longitudinal Graduation Rates": longitudinal_graduation_rates,
    "Chronic Absenteeism": chronic_absenteeism,
    "Attendance Rates": attendance_rates,
    "CCMR Rates": ccmr_rates,
    "Dropout Rates": dropout_rates,
    "STAAR Results": staar_results
}